server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3102
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml
#failed to create client manager: at least one client config must be provided
clients:
  - url: http://loki:3101/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log
#  - job_name: docker-logs
#    docker_sd_configs:
#      - host: unix:///var/run/docker.sock
#        refresh_interval: 10s
#        filters:
#          - name: label
#            values: ["logging.promtail=true"]
#    relabel_configs:
#      - source_labels: ['__meta_docker_container_name']
#        regex: '/(.*)'
#        target_label: 'container'
#      - source_labels: ['__meta_docker_container_log_stream']
#        target_label: 'logstream'
#      - source_labels: ['__meta_docker_container_label_logging_jobname']
#        target_label: 'job'