# Copied from 
# https://github.com/instantlinux/docker-tools/blob/main/images/nagiosql/docker-compose.yml
services:
  app:
    image: instantlinux/nagios:${VERSION_NAGIOS:-latest}
    restart: always
    hostname: ${NAGIOS_FQDN:-nagios.docker}
    # command: >
    #   bash -c "pip install foo &&
    #   apk add --update some-package &&
    #   ...
    #   exec /usr/local/bin/entrypoint.sh"
    environment:
      AUTHORIZED_USERS: ${NAGIOS_AUTH_USERS:-nagiosadmin}
      MAIL_RELAY_HOST: ${NAGIOS_MAIL_RELAY:-smtp}
      NGINX_PORT: ${NAGIOS_NGINX_PORT:-80}
      TZ: ${TZ:-UTC}
    volumes:
    - etc:/etc/nagios
    - var:/var/nagios
    - ${ADMIN_PATH:-/opt}/nagios/plugins:/opt/nagios/plugins:ro
    ports:
    - ${PORT_NAGIOS:-80}:80
    secrets:
    - nagios-htpasswd
    network_mode: host

  nagiosql:
    image: instantlinux/nagiosql:${VERSION_NAGIOSQL:-latest}
    restart: always
    hostname: nagiosql
    environment:
      DB_HOST: ${DB_HOST:-db00}
      NAGIOS_ETC: /etc/nagios
      TZ: ${TZ:-UTC}
    volumes:
    - config:/var/www/nagiosql/config
    - etc:/etc/nagios
    - var:/var/nagios
    ports:
    - ${PORT_NAGIOSQL:-8080}:80
    secrets:
    - nagiosql-db-password
    network_mode: bridge

  nginx:
    image: nginx:${VERSION_NGINX:-latest}
    restart: always
    hostname: monitor
    ports:
    - ${PORT_MONITOR_SSL:-443}:443
    - ${PORT_MONITOR_HTTP:-80}:80
    volumes:
    - ${ADMIN_PATH:-/opt}/nagios/etc/nginx/conf.d:/etc/nginx/conf.d:ro
    - ${SHARE_PATH:-/opt}/common/pki/ca:/etc/ssl/ca:ro
    - ${SHARE_PATH:-/opt}/common/pki/certs:/etc/ssl/certs:ro
    environment:
      TZ: ${TZ:-UTC}
    secrets:
    - monitor.${DOMAIN:-demo}-server-key.pem
    depends_on:
    - app
    - nagiosql
    network_mode: bridge
  
volumes:
  config:
  etc:
  var:

secrets:
  nagios-htpasswd:
    file: /var/adm/secrets/nagios-htpasswd
  nagiosql-db-password:
    file: /var/adm/secrets/nagiosql-db-password
  monitor.ci.net-server-key.pem:
    file: ${ADMIN_PATH}/../tls/monitor.ci.net-server-key.pem