global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    scrape_interval: 2m
    scrape_timeout: 1m
    static_configs:
      - targets: ['node_exporter:9100']
    tls_config:
      insecure_skip_verify: true
  - job_name: 'loki'
    scrape_interval: 2m
    scrape_timeout: 1m
    static_configs:
      - targets: ['loki:3101']
    tls_config:
      insecure_skip_verify: true
  - job_name: 'promtail'
    scrape_interval: 2m
    scrape_timeout: 1m
    static_configs:
      - targets: ['promtail:3102']
    tls_config:
      insecure_skip_verify: true
  - job_name: 'cadvisor'
    scrape_interval: 1m
    scrape_timeout: 30s 
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          group: 'cadvisor'
    tls_config:
      insecure_skip_verify: true